"""Maintainer subpackage - applies targeted patches to documentation.

The maintainer consumes ``EvaluationReport`` objects and produces
``MaintenanceCandidate`` records: candidate post-fix versions of
``api_reference`` plus the patch list used to derive them. A candidate is
written to the artifact store; a separate manual approval workflow gates
any DB writeback.

Strategy dispatch:

* ``DB_QUERY``    - patches sourced from ``Issue.code_value``
* ``AST_DERIVED`` - patches derived from code-side signatures
* ``LLM``         - patches generated by an LLM (v1.x; stub here)
* ``MANUAL``      - flagged in the candidate but no patch is produced
"""

from doc_quality.maintainer.maintainer import DocQualityMaintainer

__all__ = ["DocQualityMaintainer"]
